import AppKit
import Foundation

/// Polls the general pasteboard and records new contents.
@MainActor
final class ClipboardMonitor {
    private let store: ClipboardStore
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Images larger than this are recorded as text-less placeholders rather than copied to disk.
    private let maxImageBytes = 32 * 1024 * 1024

    /// Pasteboard types set by password managers that ask not to be recorded.
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("com.typeit4me.clipping")
    ]

    init(store: ClipboardStore) {
        self.store = store
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call before writing to the pasteboard so our own write isn't re-recorded verbatim.
    func acknowledgeOwnWrite() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        capture(from: pb)
    }

    private func capture(from pb: NSPasteboard) {
        let types = pb.types ?? []
        guard !types.isEmpty else { return }
        if types.contains(where: { Self.concealedTypes.contains($0) }) { return }

        let source = NSWorkspace.shared.frontmostApplication
        let appName = source?.localizedName
        let bundleID = source?.bundleIdentifier

        if let item = fileItem(from: pb, appName: appName, bundleID: bundleID) {
            store.insert(item)
            return
        }
        if let item = imageItem(from: pb, appName: appName, bundleID: bundleID) {
            store.insert(item)
            return
        }
        if let item = textItem(from: pb, appName: appName, bundleID: bundleID) {
            store.insert(item)
        }
    }

    private func fileItem(from pb: NSPasteboard, appName: String?, bundleID: String?) -> ClipboardItem? {
        guard let urls = pb.readObjects(forClasses: [NSURL.self],
                                        options: [.urlReadingFileURLsOnly: true]) as? [URL],
              !urls.isEmpty else { return nil }
        let paths = urls.map(\.path).joined(separator: "\n")
        let bytes = urls.reduce(0) { total, url in
            let size = (try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0
            return total + size
        }
        return ClipboardItem(
            kind: .files,
            text: paths,
            byteCount: bytes,
            fingerprint: ClipboardStore.fingerprint(Data(("files:" + paths).utf8)),
            sourceAppName: appName,
            sourceBundleID: bundleID
        )
    }

    private func imageItem(from pb: NSPasteboard, appName: String?, bundleID: String?) -> ClipboardItem? {
        let imageTypes: [NSPasteboard.PasteboardType] = [.png, .tiff]
        guard let type = imageTypes.first(where: { pb.data(forType: $0) != nil }),
              let raw = pb.data(forType: type),
              raw.count <= maxImageBytes,
              let rep = NSBitmapImageRep(data: raw) else { return nil }

        guard let png = type == .png ? raw : rep.representation(using: .png, properties: [:]) else { return nil }
        let thumb = ImageTools.thumbnailPNG(from: rep, maxDimension: 220)
        let files = store.storeImage(pngData: png, thumbData: thumb)

        return ClipboardItem(
            kind: .image,
            text: "",
            imageFile: files.image,
            thumbFile: files.thumb,
            pixelWidth: rep.pixelsWide,
            pixelHeight: rep.pixelsHigh,
            byteCount: png.count,
            fingerprint: ClipboardStore.fingerprint(png),
            sourceAppName: appName,
            sourceBundleID: bundleID
        )
    }

    private func textItem(from pb: NSPasteboard, appName: String?, bundleID: String?) -> ClipboardItem? {
        guard let text = pb.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        return ClipboardItem(
            kind: .text,
            text: text,
            byteCount: text.utf8.count,
            fingerprint: ClipboardStore.fingerprint(Data(("text:" + text).utf8)),
            sourceAppName: appName,
            sourceBundleID: bundleID
        )
    }
}

enum ImageTools {
    /// Aspect-preserving downscale, returned as PNG data.
    static func thumbnailPNG(from rep: NSBitmapImageRep, maxDimension: CGFloat) -> Data? {
        let width = CGFloat(rep.pixelsWide)
        let height = CGFloat(rep.pixelsHigh)
        guard width > 0, height > 0 else { return nil }
        let scale = min(1, maxDimension / max(width, height))
        let targetWidth = max(1, Int((width * scale).rounded()))
        let targetHeight = max(1, Int((height * scale).rounded()))

        guard let target = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: targetWidth,
            pixelsHigh: targetHeight,
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        ) else { return nil }
        target.size = NSSize(width: targetWidth, height: targetHeight)

        NSGraphicsContext.saveGraphicsState()
        defer { NSGraphicsContext.restoreGraphicsState() }
        guard let context = NSGraphicsContext(bitmapImageRep: target) else { return nil }
        NSGraphicsContext.current = context
        context.imageInterpolation = .high
        rep.draw(in: NSRect(x: 0, y: 0, width: targetWidth, height: targetHeight))
        context.flushGraphics()

        return target.representation(using: .png, properties: [:])
    }
}
